# Generated by Django 5.2.1 on 2025-08-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_alter_chatmessage_options_chatmessage_session_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="net_user_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
