# Generated by Django 5.2.1 on 2025-08-16 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_chatmessage_net_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmessage",
            name="net_user_id",
        ),
    ]
